### ISSUE TITLE
🚧 TODOs

### ISSUE THREAD

**Issue by ericksantos12** [ericksantos12/ValidadorJS#2]
# TODO:

- [x] Montar webserver que escute na porta 4250 ou 7777
- [x] Criar um diretorio chamado "entrada", possibilitando inserção de arquivos markdown
- [x] Adicionar favicon

- [x] Apresentar 5 paginas
    - [x] Index
        - [x] Criar rota (#4)
    - [x] Entrada
        - [x] Criar rota
        - [x] Ler arquivo
        - [x] Mostrar na tela o texto do arquivo 
    - [x] Links
        - [x] Criar rota
        - [x] Ler arquivo
        - [x] Demonstrar links contidos
        - [x] Mostrar erro caso não haja links
    - [x] Validar
        - [x] Criar rota
        - [x] Ler o arquivo
        - [x] Demosntrar o status code 200 ou 404
    - [x] 404
        - [x] Criar rota (#4)
